### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by vaibhavviswanathan** [adinriv/docker-opencv#1]
Hi! 

Thanks for making this docker repo. I have tried downloading and building this with a simple python app that imports cv2, however I get the error: "ImportError: No module named cv2". Could you help please?

Best,
Vai

**Comment by so77id** [comment]
hi @vaibhavviswanathan,

this repo is created for use `python3` with `OpenCV` if you use the simple `python` command you will get this error

<img width="505" alt="screen shot 2017-08-15 at 00 39 33" src="https://user-images.githubusercontent.com/4089219/29301377-1ae7dfc0-8152-11e7-9d45-afaeec150490.png">

This is because `python` command use the version 2.7 of python.  On the contrary if you use the `python3` command, you will not have problems using `OpenCV`

<img width="505" alt="screen shot 2017-08-15 at 00 39 57" src="https://user-images.githubusercontent.com/4089219/29301429-746d186c-8152-11e7-9356-5d0191dcef2a.png">
